// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	pdf "github.com/EduGoGroup/edugo-worker/internal/infrastructure/pdf"
)

// MockExtractor is an autogenerated mock type for the Extractor type
type MockExtractor struct {
	mock.Mock
}

type MockExtractor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExtractor) EXPECT() *MockExtractor_Expecter {
	return &MockExtractor_Expecter{mock: &_m.Mock}
}

// Extract provides a mock function with given fields: ctx, reader
func (_m *MockExtractor) Extract(ctx context.Context, reader io.Reader) (string, error) {
	ret := _m.Called(ctx, reader)

	if len(ret) == 0 {
		panic("no return value specified for Extract")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader) (string, error)); ok {
		return rf(ctx, reader)
	}
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader) string); ok {
		r0 = rf(ctx, reader)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, io.Reader) error); ok {
		r1 = rf(ctx, reader)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExtractor_Extract_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Extract'
type MockExtractor_Extract_Call struct {
	*mock.Call
}

// Extract is a helper method to define mock.On call
//   - ctx context.Context
//   - reader io.Reader
func (_e *MockExtractor_Expecter) Extract(ctx interface{}, reader interface{}) *MockExtractor_Extract_Call {
	return &MockExtractor_Extract_Call{Call: _e.mock.On("Extract", ctx, reader)}
}

func (_c *MockExtractor_Extract_Call) Run(run func(ctx context.Context, reader io.Reader)) *MockExtractor_Extract_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(io.Reader))
	})
	return _c
}

func (_c *MockExtractor_Extract_Call) Return(_a0 string, _a1 error) *MockExtractor_Extract_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExtractor_Extract_Call) RunAndReturn(run func(context.Context, io.Reader) (string, error)) *MockExtractor_Extract_Call {
	_c.Call.Return(run)
	return _c
}

// ExtractWithMetadata provides a mock function with given fields: ctx, reader
func (_m *MockExtractor) ExtractWithMetadata(ctx context.Context, reader io.Reader) (*pdf.ExtractionResult, error) {
	ret := _m.Called(ctx, reader)

	if len(ret) == 0 {
		panic("no return value specified for ExtractWithMetadata")
	}

	var r0 *pdf.ExtractionResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader) (*pdf.ExtractionResult, error)); ok {
		return rf(ctx, reader)
	}
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader) *pdf.ExtractionResult); ok {
		r0 = rf(ctx, reader)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pdf.ExtractionResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, io.Reader) error); ok {
		r1 = rf(ctx, reader)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExtractor_ExtractWithMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractWithMetadata'
type MockExtractor_ExtractWithMetadata_Call struct {
	*mock.Call
}

// ExtractWithMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - reader io.Reader
func (_e *MockExtractor_Expecter) ExtractWithMetadata(ctx interface{}, reader interface{}) *MockExtractor_ExtractWithMetadata_Call {
	return &MockExtractor_ExtractWithMetadata_Call{Call: _e.mock.On("ExtractWithMetadata", ctx, reader)}
}

func (_c *MockExtractor_ExtractWithMetadata_Call) Run(run func(ctx context.Context, reader io.Reader)) *MockExtractor_ExtractWithMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(io.Reader))
	})
	return _c
}

func (_c *MockExtractor_ExtractWithMetadata_Call) Return(_a0 *pdf.ExtractionResult, _a1 error) *MockExtractor_ExtractWithMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExtractor_ExtractWithMetadata_Call) RunAndReturn(run func(context.Context, io.Reader) (*pdf.ExtractionResult, error)) *MockExtractor_ExtractWithMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExtractor creates a new instance of MockExtractor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExtractor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExtractor {
	mock := &MockExtractor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
