// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockCleaner is an autogenerated mock type for the Cleaner type
type MockCleaner struct {
	mock.Mock
}

type MockCleaner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCleaner) EXPECT() *MockCleaner_Expecter {
	return &MockCleaner_Expecter{mock: &_m.Mock}
}

// Clean provides a mock function with given fields: text
func (_m *MockCleaner) Clean(text string) string {
	ret := _m.Called(text)

	if len(ret) == 0 {
		panic("no return value specified for Clean")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(text)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockCleaner_Clean_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clean'
type MockCleaner_Clean_Call struct {
	*mock.Call
}

// Clean is a helper method to define mock.On call
//   - text string
func (_e *MockCleaner_Expecter) Clean(text interface{}) *MockCleaner_Clean_Call {
	return &MockCleaner_Clean_Call{Call: _e.mock.On("Clean", text)}
}

func (_c *MockCleaner_Clean_Call) Run(run func(text string)) *MockCleaner_Clean_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCleaner_Clean_Call) Return(_a0 string) *MockCleaner_Clean_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCleaner_Clean_Call) RunAndReturn(run func(string) string) *MockCleaner_Clean_Call {
	_c.Call.Return(run)
	return _c
}

// NormalizeSpaces provides a mock function with given fields: text
func (_m *MockCleaner) NormalizeSpaces(text string) string {
	ret := _m.Called(text)

	if len(ret) == 0 {
		panic("no return value specified for NormalizeSpaces")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(text)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockCleaner_NormalizeSpaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NormalizeSpaces'
type MockCleaner_NormalizeSpaces_Call struct {
	*mock.Call
}

// NormalizeSpaces is a helper method to define mock.On call
//   - text string
func (_e *MockCleaner_Expecter) NormalizeSpaces(text interface{}) *MockCleaner_NormalizeSpaces_Call {
	return &MockCleaner_NormalizeSpaces_Call{Call: _e.mock.On("NormalizeSpaces", text)}
}

func (_c *MockCleaner_NormalizeSpaces_Call) Run(run func(text string)) *MockCleaner_NormalizeSpaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCleaner_NormalizeSpaces_Call) Return(_a0 string) *MockCleaner_NormalizeSpaces_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCleaner_NormalizeSpaces_Call) RunAndReturn(run func(string) string) *MockCleaner_NormalizeSpaces_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveHeaders provides a mock function with given fields: text
func (_m *MockCleaner) RemoveHeaders(text string) string {
	ret := _m.Called(text)

	if len(ret) == 0 {
		panic("no return value specified for RemoveHeaders")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(text)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockCleaner_RemoveHeaders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveHeaders'
type MockCleaner_RemoveHeaders_Call struct {
	*mock.Call
}

// RemoveHeaders is a helper method to define mock.On call
//   - text string
func (_e *MockCleaner_Expecter) RemoveHeaders(text interface{}) *MockCleaner_RemoveHeaders_Call {
	return &MockCleaner_RemoveHeaders_Call{Call: _e.mock.On("RemoveHeaders", text)}
}

func (_c *MockCleaner_RemoveHeaders_Call) Run(run func(text string)) *MockCleaner_RemoveHeaders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCleaner_RemoveHeaders_Call) Return(_a0 string) *MockCleaner_RemoveHeaders_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCleaner_RemoveHeaders_Call) RunAndReturn(run func(string) string) *MockCleaner_RemoveHeaders_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCleaner creates a new instance of MockCleaner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCleaner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCleaner {
	mock := &MockCleaner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
