// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	nlp "github.com/EduGoGroup/edugo-worker/internal/infrastructure/nlp"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// GenerateQuiz provides a mock function with given fields: ctx, text, questionCount
func (_m *MockClient) GenerateQuiz(ctx context.Context, text string, questionCount int) (*nlp.Quiz, error) {
	ret := _m.Called(ctx, text, questionCount)

	if len(ret) == 0 {
		panic("no return value specified for GenerateQuiz")
	}

	var r0 *nlp.Quiz
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (*nlp.Quiz, error)); ok {
		return rf(ctx, text, questionCount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) *nlp.Quiz); ok {
		r0 = rf(ctx, text, questionCount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*nlp.Quiz)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, text, questionCount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GenerateQuiz_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateQuiz'
type MockClient_GenerateQuiz_Call struct {
	*mock.Call
}

// GenerateQuiz is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
//   - questionCount int
func (_e *MockClient_Expecter) GenerateQuiz(ctx interface{}, text interface{}, questionCount interface{}) *MockClient_GenerateQuiz_Call {
	return &MockClient_GenerateQuiz_Call{Call: _e.mock.On("GenerateQuiz", ctx, text, questionCount)}
}

func (_c *MockClient_GenerateQuiz_Call) Run(run func(ctx context.Context, text string, questionCount int)) *MockClient_GenerateQuiz_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockClient_GenerateQuiz_Call) Return(_a0 *nlp.Quiz, _a1 error) *MockClient_GenerateQuiz_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GenerateQuiz_Call) RunAndReturn(run func(context.Context, string, int) (*nlp.Quiz, error)) *MockClient_GenerateQuiz_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateSummary provides a mock function with given fields: ctx, text
func (_m *MockClient) GenerateSummary(ctx context.Context, text string) (*nlp.Summary, error) {
	ret := _m.Called(ctx, text)

	if len(ret) == 0 {
		panic("no return value specified for GenerateSummary")
	}

	var r0 *nlp.Summary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*nlp.Summary, error)); ok {
		return rf(ctx, text)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *nlp.Summary); ok {
		r0 = rf(ctx, text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*nlp.Summary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, text)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GenerateSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateSummary'
type MockClient_GenerateSummary_Call struct {
	*mock.Call
}

// GenerateSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
func (_e *MockClient_Expecter) GenerateSummary(ctx interface{}, text interface{}) *MockClient_GenerateSummary_Call {
	return &MockClient_GenerateSummary_Call{Call: _e.mock.On("GenerateSummary", ctx, text)}
}

func (_c *MockClient_GenerateSummary_Call) Run(run func(ctx context.Context, text string)) *MockClient_GenerateSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_GenerateSummary_Call) Return(_a0 *nlp.Summary, _a1 error) *MockClient_GenerateSummary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GenerateSummary_Call) RunAndReturn(run func(context.Context, string) (*nlp.Summary, error)) *MockClient_GenerateSummary_Call {
	_c.Call.Return(run)
	return _c
}

// HealthCheck provides a mock function with given fields: ctx
func (_m *MockClient) HealthCheck(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_HealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthCheck'
type MockClient_HealthCheck_Call struct {
	*mock.Call
}

// HealthCheck is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) HealthCheck(ctx interface{}) *MockClient_HealthCheck_Call {
	return &MockClient_HealthCheck_Call{Call: _e.mock.On("HealthCheck", ctx)}
}

func (_c *MockClient_HealthCheck_Call) Run(run func(ctx context.Context)) *MockClient_HealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockClient_HealthCheck_Call) Return(_a0 error) *MockClient_HealthCheck_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_HealthCheck_Call) RunAndReturn(run func(context.Context) error) *MockClient_HealthCheck_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
