messaging:
  rabbitmq:
    url: "amqps://rgvtxvma:O_9EeTgx8IHDg3MW3UZuTGn1tdbdhsZR@chameleon.lmq.cloudamqp.com/rgvtxvma"

logging:
  level: "debug"
  format: "json"

api_identity:
  base_url: "http://localhost:8070/api"
