// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/EduGoGroup/edugo-infrastructure/mongodb/entities"
	mock "github.com/stretchr/testify/mock"

	"go.mongodb.org/mongo-driver/v2/bson"

	time "time"
)

// MockMaterialEventRepository is an autogenerated mock type for the MaterialEventRepository type
type MockMaterialEventRepository struct {
	mock.Mock
}

type MockMaterialEventRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMaterialEventRepository) EXPECT() *MockMaterialEventRepository_Expecter {
	return &MockMaterialEventRepository_Expecter{mock: &_m.Mock}
}

// CountByEventType provides a mock function with given fields: ctx, eventType
func (_m *MockMaterialEventRepository) CountByEventType(ctx context.Context, eventType string) (int64, error) {
	ret := _m.Called(ctx, eventType)

	if len(ret) == 0 {
		panic("no return value specified for CountByEventType")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, eventType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, eventType)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, eventType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMaterialEventRepository_CountByEventType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByEventType'
type MockMaterialEventRepository_CountByEventType_Call struct {
	*mock.Call
}

// CountByEventType is a helper method to define mock.On call
//   - ctx context.Context
//   - eventType string
func (_e *MockMaterialEventRepository_Expecter) CountByEventType(ctx interface{}, eventType interface{}) *MockMaterialEventRepository_CountByEventType_Call {
	return &MockMaterialEventRepository_CountByEventType_Call{Call: _e.mock.On("CountByEventType", ctx, eventType)}
}

func (_c *MockMaterialEventRepository_CountByEventType_Call) Run(run func(ctx context.Context, eventType string)) *MockMaterialEventRepository_CountByEventType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMaterialEventRepository_CountByEventType_Call) Return(_a0 int64, _a1 error) *MockMaterialEventRepository_CountByEventType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMaterialEventRepository_CountByEventType_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockMaterialEventRepository_CountByEventType_Call {
	_c.Call.Return(run)
	return _c
}

// CountByStatus provides a mock function with given fields: ctx, status
func (_m *MockMaterialEventRepository) CountByStatus(ctx context.Context, status string) (int64, error) {
	ret := _m.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for CountByStatus")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, status)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMaterialEventRepository_CountByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByStatus'
type MockMaterialEventRepository_CountByStatus_Call struct {
	*mock.Call
}

// CountByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status string
func (_e *MockMaterialEventRepository_Expecter) CountByStatus(ctx interface{}, status interface{}) *MockMaterialEventRepository_CountByStatus_Call {
	return &MockMaterialEventRepository_CountByStatus_Call{Call: _e.mock.On("CountByStatus", ctx, status)}
}

func (_c *MockMaterialEventRepository_CountByStatus_Call) Run(run func(ctx context.Context, status string)) *MockMaterialEventRepository_CountByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMaterialEventRepository_CountByStatus_Call) Return(_a0 int64, _a1 error) *MockMaterialEventRepository_CountByStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMaterialEventRepository_CountByStatus_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockMaterialEventRepository_CountByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, event
func (_m *MockMaterialEventRepository) Create(ctx context.Context, event *entities.MaterialEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.MaterialEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMaterialEventRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMaterialEventRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - event *entities.MaterialEvent
func (_e *MockMaterialEventRepository_Expecter) Create(ctx interface{}, event interface{}) *MockMaterialEventRepository_Create_Call {
	return &MockMaterialEventRepository_Create_Call{Call: _e.mock.On("Create", ctx, event)}
}

func (_c *MockMaterialEventRepository_Create_Call) Run(run func(ctx context.Context, event *entities.MaterialEvent)) *MockMaterialEventRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.MaterialEvent))
	})
	return _c
}

func (_c *MockMaterialEventRepository_Create_Call) Return(_a0 error) *MockMaterialEventRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMaterialEventRepository_Create_Call) RunAndReturn(run func(context.Context, *entities.MaterialEvent) error) *MockMaterialEventRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOldEvents provides a mock function with given fields: ctx, olderThan
func (_m *MockMaterialEventRepository) DeleteOldEvents(ctx context.Context, olderThan time.Time) (int64, error) {
	ret := _m.Called(ctx, olderThan)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOldEvents")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return rf(ctx, olderThan)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = rf(ctx, olderThan)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, olderThan)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMaterialEventRepository_DeleteOldEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOldEvents'
type MockMaterialEventRepository_DeleteOldEvents_Call struct {
	*mock.Call
}

// DeleteOldEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - olderThan time.Time
func (_e *MockMaterialEventRepository_Expecter) DeleteOldEvents(ctx interface{}, olderThan interface{}) *MockMaterialEventRepository_DeleteOldEvents_Call {
	return &MockMaterialEventRepository_DeleteOldEvents_Call{Call: _e.mock.On("DeleteOldEvents", ctx, olderThan)}
}

func (_c *MockMaterialEventRepository_DeleteOldEvents_Call) Run(run func(ctx context.Context, olderThan time.Time)) *MockMaterialEventRepository_DeleteOldEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockMaterialEventRepository_DeleteOldEvents_Call) Return(_a0 int64, _a1 error) *MockMaterialEventRepository_DeleteOldEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMaterialEventRepository_DeleteOldEvents_Call) RunAndReturn(run func(context.Context, time.Time) (int64, error)) *MockMaterialEventRepository_DeleteOldEvents_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEventType provides a mock function with given fields: ctx, eventType, limit
func (_m *MockMaterialEventRepository) FindByEventType(ctx context.Context, eventType string, limit int64) ([]*entities.MaterialEvent, error) {
	ret := _m.Called(ctx, eventType, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByEventType")
	}

	var r0 []*entities.MaterialEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) ([]*entities.MaterialEvent, error)); ok {
		return rf(ctx, eventType, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) []*entities.MaterialEvent); ok {
		r0 = rf(ctx, eventType, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.MaterialEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, eventType, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMaterialEventRepository_FindByEventType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEventType'
type MockMaterialEventRepository_FindByEventType_Call struct {
	*mock.Call
}

// FindByEventType is a helper method to define mock.On call
//   - ctx context.Context
//   - eventType string
//   - limit int64
func (_e *MockMaterialEventRepository_Expecter) FindByEventType(ctx interface{}, eventType interface{}, limit interface{}) *MockMaterialEventRepository_FindByEventType_Call {
	return &MockMaterialEventRepository_FindByEventType_Call{Call: _e.mock.On("FindByEventType", ctx, eventType, limit)}
}

func (_c *MockMaterialEventRepository_FindByEventType_Call) Run(run func(ctx context.Context, eventType string, limit int64)) *MockMaterialEventRepository_FindByEventType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *MockMaterialEventRepository_FindByEventType_Call) Return(_a0 []*entities.MaterialEvent, _a1 error) *MockMaterialEventRepository_FindByEventType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMaterialEventRepository_FindByEventType_Call) RunAndReturn(run func(context.Context, string, int64) ([]*entities.MaterialEvent, error)) *MockMaterialEventRepository_FindByEventType_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockMaterialEventRepository) FindByID(ctx context.Context, id bson.ObjectID) (*entities.MaterialEvent, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.MaterialEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bson.ObjectID) (*entities.MaterialEvent, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bson.ObjectID) *entities.MaterialEvent); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.MaterialEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bson.ObjectID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMaterialEventRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockMaterialEventRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id bson.ObjectID
func (_e *MockMaterialEventRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockMaterialEventRepository_FindByID_Call {
	return &MockMaterialEventRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockMaterialEventRepository_FindByID_Call) Run(run func(ctx context.Context, id bson.ObjectID)) *MockMaterialEventRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bson.ObjectID))
	})
	return _c
}

func (_c *MockMaterialEventRepository_FindByID_Call) Return(_a0 *entities.MaterialEvent, _a1 error) *MockMaterialEventRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMaterialEventRepository_FindByID_Call) RunAndReturn(run func(context.Context, bson.ObjectID) (*entities.MaterialEvent, error)) *MockMaterialEventRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByMaterialID provides a mock function with given fields: ctx, materialID, limit
func (_m *MockMaterialEventRepository) FindByMaterialID(ctx context.Context, materialID string, limit int64) ([]*entities.MaterialEvent, error) {
	ret := _m.Called(ctx, materialID, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByMaterialID")
	}

	var r0 []*entities.MaterialEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) ([]*entities.MaterialEvent, error)); ok {
		return rf(ctx, materialID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) []*entities.MaterialEvent); ok {
		r0 = rf(ctx, materialID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.MaterialEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, materialID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMaterialEventRepository_FindByMaterialID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByMaterialID'
type MockMaterialEventRepository_FindByMaterialID_Call struct {
	*mock.Call
}

// FindByMaterialID is a helper method to define mock.On call
//   - ctx context.Context
//   - materialID string
//   - limit int64
func (_e *MockMaterialEventRepository_Expecter) FindByMaterialID(ctx interface{}, materialID interface{}, limit interface{}) *MockMaterialEventRepository_FindByMaterialID_Call {
	return &MockMaterialEventRepository_FindByMaterialID_Call{Call: _e.mock.On("FindByMaterialID", ctx, materialID, limit)}
}

func (_c *MockMaterialEventRepository_FindByMaterialID_Call) Run(run func(ctx context.Context, materialID string, limit int64)) *MockMaterialEventRepository_FindByMaterialID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *MockMaterialEventRepository_FindByMaterialID_Call) Return(_a0 []*entities.MaterialEvent, _a1 error) *MockMaterialEventRepository_FindByMaterialID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMaterialEventRepository_FindByMaterialID_Call) RunAndReturn(run func(context.Context, string, int64) ([]*entities.MaterialEvent, error)) *MockMaterialEventRepository_FindByMaterialID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByStatus provides a mock function with given fields: ctx, status, limit
func (_m *MockMaterialEventRepository) FindByStatus(ctx context.Context, status string, limit int64) ([]*entities.MaterialEvent, error) {
	ret := _m.Called(ctx, status, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByStatus")
	}

	var r0 []*entities.MaterialEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) ([]*entities.MaterialEvent, error)); ok {
		return rf(ctx, status, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) []*entities.MaterialEvent); ok {
		r0 = rf(ctx, status, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.MaterialEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, status, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMaterialEventRepository_FindByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByStatus'
type MockMaterialEventRepository_FindByStatus_Call struct {
	*mock.Call
}

// FindByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status string
//   - limit int64
func (_e *MockMaterialEventRepository_Expecter) FindByStatus(ctx interface{}, status interface{}, limit interface{}) *MockMaterialEventRepository_FindByStatus_Call {
	return &MockMaterialEventRepository_FindByStatus_Call{Call: _e.mock.On("FindByStatus", ctx, status, limit)}
}

func (_c *MockMaterialEventRepository_FindByStatus_Call) Run(run func(ctx context.Context, status string, limit int64)) *MockMaterialEventRepository_FindByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *MockMaterialEventRepository_FindByStatus_Call) Return(_a0 []*entities.MaterialEvent, _a1 error) *MockMaterialEventRepository_FindByStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMaterialEventRepository_FindByStatus_Call) RunAndReturn(run func(context.Context, string, int64) ([]*entities.MaterialEvent, error)) *MockMaterialEventRepository_FindByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// FindFailedEvents provides a mock function with given fields: ctx, maxRetries, limit
func (_m *MockMaterialEventRepository) FindFailedEvents(ctx context.Context, maxRetries int, limit int64) ([]*entities.MaterialEvent, error) {
	ret := _m.Called(ctx, maxRetries, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindFailedEvents")
	}

	var r0 []*entities.MaterialEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int64) ([]*entities.MaterialEvent, error)); ok {
		return rf(ctx, maxRetries, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int64) []*entities.MaterialEvent); ok {
		r0 = rf(ctx, maxRetries, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.MaterialEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int64) error); ok {
		r1 = rf(ctx, maxRetries, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMaterialEventRepository_FindFailedEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindFailedEvents'
type MockMaterialEventRepository_FindFailedEvents_Call struct {
	*mock.Call
}

// FindFailedEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - maxRetries int
//   - limit int64
func (_e *MockMaterialEventRepository_Expecter) FindFailedEvents(ctx interface{}, maxRetries interface{}, limit interface{}) *MockMaterialEventRepository_FindFailedEvents_Call {
	return &MockMaterialEventRepository_FindFailedEvents_Call{Call: _e.mock.On("FindFailedEvents", ctx, maxRetries, limit)}
}

func (_c *MockMaterialEventRepository_FindFailedEvents_Call) Run(run func(ctx context.Context, maxRetries int, limit int64)) *MockMaterialEventRepository_FindFailedEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int64))
	})
	return _c
}

func (_c *MockMaterialEventRepository_FindFailedEvents_Call) Return(_a0 []*entities.MaterialEvent, _a1 error) *MockMaterialEventRepository_FindFailedEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMaterialEventRepository_FindFailedEvents_Call) RunAndReturn(run func(context.Context, int, int64) ([]*entities.MaterialEvent, error)) *MockMaterialEventRepository_FindFailedEvents_Call {
	_c.Call.Return(run)
	return _c
}

// FindPendingEvents provides a mock function with given fields: ctx, limit
func (_m *MockMaterialEventRepository) FindPendingEvents(ctx context.Context, limit int64) ([]*entities.MaterialEvent, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindPendingEvents")
	}

	var r0 []*entities.MaterialEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]*entities.MaterialEvent, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*entities.MaterialEvent); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.MaterialEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMaterialEventRepository_FindPendingEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPendingEvents'
type MockMaterialEventRepository_FindPendingEvents_Call struct {
	*mock.Call
}

// FindPendingEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int64
func (_e *MockMaterialEventRepository_Expecter) FindPendingEvents(ctx interface{}, limit interface{}) *MockMaterialEventRepository_FindPendingEvents_Call {
	return &MockMaterialEventRepository_FindPendingEvents_Call{Call: _e.mock.On("FindPendingEvents", ctx, limit)}
}

func (_c *MockMaterialEventRepository_FindPendingEvents_Call) Run(run func(ctx context.Context, limit int64)) *MockMaterialEventRepository_FindPendingEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockMaterialEventRepository_FindPendingEvents_Call) Return(_a0 []*entities.MaterialEvent, _a1 error) *MockMaterialEventRepository_FindPendingEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMaterialEventRepository_FindPendingEvents_Call) RunAndReturn(run func(context.Context, int64) ([]*entities.MaterialEvent, error)) *MockMaterialEventRepository_FindPendingEvents_Call {
	_c.Call.Return(run)
	return _c
}

// FindRecent provides a mock function with given fields: ctx, limit
func (_m *MockMaterialEventRepository) FindRecent(ctx context.Context, limit int64) ([]*entities.MaterialEvent, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindRecent")
	}

	var r0 []*entities.MaterialEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]*entities.MaterialEvent, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*entities.MaterialEvent); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.MaterialEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMaterialEventRepository_FindRecent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRecent'
type MockMaterialEventRepository_FindRecent_Call struct {
	*mock.Call
}

// FindRecent is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int64
func (_e *MockMaterialEventRepository_Expecter) FindRecent(ctx interface{}, limit interface{}) *MockMaterialEventRepository_FindRecent_Call {
	return &MockMaterialEventRepository_FindRecent_Call{Call: _e.mock.On("FindRecent", ctx, limit)}
}

func (_c *MockMaterialEventRepository_FindRecent_Call) Run(run func(ctx context.Context, limit int64)) *MockMaterialEventRepository_FindRecent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockMaterialEventRepository_FindRecent_Call) Return(_a0 []*entities.MaterialEvent, _a1 error) *MockMaterialEventRepository_FindRecent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMaterialEventRepository_FindRecent_Call) RunAndReturn(run func(context.Context, int64) ([]*entities.MaterialEvent, error)) *MockMaterialEventRepository_FindRecent_Call {
	_c.Call.Return(run)
	return _c
}

// GetEventStatistics provides a mock function with given fields: ctx
func (_m *MockMaterialEventRepository) GetEventStatistics(ctx context.Context) (map[string]int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetEventStatistics")
	}

	var r0 map[string]int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]int64); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMaterialEventRepository_GetEventStatistics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventStatistics'
type MockMaterialEventRepository_GetEventStatistics_Call struct {
	*mock.Call
}

// GetEventStatistics is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMaterialEventRepository_Expecter) GetEventStatistics(ctx interface{}) *MockMaterialEventRepository_GetEventStatistics_Call {
	return &MockMaterialEventRepository_GetEventStatistics_Call{Call: _e.mock.On("GetEventStatistics", ctx)}
}

func (_c *MockMaterialEventRepository_GetEventStatistics_Call) Run(run func(ctx context.Context)) *MockMaterialEventRepository_GetEventStatistics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMaterialEventRepository_GetEventStatistics_Call) Return(_a0 map[string]int64, _a1 error) *MockMaterialEventRepository_GetEventStatistics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMaterialEventRepository_GetEventStatistics_Call) RunAndReturn(run func(context.Context) (map[string]int64, error)) *MockMaterialEventRepository_GetEventStatistics_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, event
func (_m *MockMaterialEventRepository) Update(ctx context.Context, event *entities.MaterialEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.MaterialEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMaterialEventRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockMaterialEventRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - event *entities.MaterialEvent
func (_e *MockMaterialEventRepository_Expecter) Update(ctx interface{}, event interface{}) *MockMaterialEventRepository_Update_Call {
	return &MockMaterialEventRepository_Update_Call{Call: _e.mock.On("Update", ctx, event)}
}

func (_c *MockMaterialEventRepository_Update_Call) Run(run func(ctx context.Context, event *entities.MaterialEvent)) *MockMaterialEventRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.MaterialEvent))
	})
	return _c
}

func (_c *MockMaterialEventRepository_Update_Call) Return(_a0 error) *MockMaterialEventRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMaterialEventRepository_Update_Call) RunAndReturn(run func(context.Context, *entities.MaterialEvent) error) *MockMaterialEventRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMaterialEventRepository creates a new instance of MockMaterialEventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMaterialEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMaterialEventRepository {
	mock := &MockMaterialEventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
