// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/EduGoGroup/edugo-infrastructure/mongodb/entities"
	mock "github.com/stretchr/testify/mock"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// MockMaterialAssessmentRepository is an autogenerated mock type for the MaterialAssessmentRepository type
type MockMaterialAssessmentRepository struct {
	mock.Mock
}

type MockMaterialAssessmentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMaterialAssessmentRepository) EXPECT() *MockMaterialAssessmentRepository_Expecter {
	return &MockMaterialAssessmentRepository_Expecter{mock: &_m.Mock}
}

// CountByTotalPoints provides a mock function with given fields: ctx, minPoints, maxPoints
func (_m *MockMaterialAssessmentRepository) CountByTotalPoints(ctx context.Context, minPoints int, maxPoints int) (int64, error) {
	ret := _m.Called(ctx, minPoints, maxPoints)

	if len(ret) == 0 {
		panic("no return value specified for CountByTotalPoints")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (int64, error)); ok {
		return rf(ctx, minPoints, maxPoints)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) int64); ok {
		r0 = rf(ctx, minPoints, maxPoints)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, minPoints, maxPoints)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMaterialAssessmentRepository_CountByTotalPoints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByTotalPoints'
type MockMaterialAssessmentRepository_CountByTotalPoints_Call struct {
	*mock.Call
}

// CountByTotalPoints is a helper method to define mock.On call
//   - ctx context.Context
//   - minPoints int
//   - maxPoints int
func (_e *MockMaterialAssessmentRepository_Expecter) CountByTotalPoints(ctx interface{}, minPoints interface{}, maxPoints interface{}) *MockMaterialAssessmentRepository_CountByTotalPoints_Call {
	return &MockMaterialAssessmentRepository_CountByTotalPoints_Call{Call: _e.mock.On("CountByTotalPoints", ctx, minPoints, maxPoints)}
}

func (_c *MockMaterialAssessmentRepository_CountByTotalPoints_Call) Run(run func(ctx context.Context, minPoints int, maxPoints int)) *MockMaterialAssessmentRepository_CountByTotalPoints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockMaterialAssessmentRepository_CountByTotalPoints_Call) Return(_a0 int64, _a1 error) *MockMaterialAssessmentRepository_CountByTotalPoints_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMaterialAssessmentRepository_CountByTotalPoints_Call) RunAndReturn(run func(context.Context, int, int) (int64, error)) *MockMaterialAssessmentRepository_CountByTotalPoints_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, assessment
func (_m *MockMaterialAssessmentRepository) Create(ctx context.Context, assessment *entities.MaterialAssessment) error {
	ret := _m.Called(ctx, assessment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.MaterialAssessment) error); ok {
		r0 = rf(ctx, assessment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMaterialAssessmentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMaterialAssessmentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - assessment *entities.MaterialAssessment
func (_e *MockMaterialAssessmentRepository_Expecter) Create(ctx interface{}, assessment interface{}) *MockMaterialAssessmentRepository_Create_Call {
	return &MockMaterialAssessmentRepository_Create_Call{Call: _e.mock.On("Create", ctx, assessment)}
}

func (_c *MockMaterialAssessmentRepository_Create_Call) Run(run func(ctx context.Context, assessment *entities.MaterialAssessment)) *MockMaterialAssessmentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.MaterialAssessment))
	})
	return _c
}

func (_c *MockMaterialAssessmentRepository_Create_Call) Return(_a0 error) *MockMaterialAssessmentRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMaterialAssessmentRepository_Create_Call) RunAndReturn(run func(context.Context, *entities.MaterialAssessment) error) *MockMaterialAssessmentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, materialID
func (_m *MockMaterialAssessmentRepository) Delete(ctx context.Context, materialID string) error {
	ret := _m.Called(ctx, materialID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, materialID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMaterialAssessmentRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockMaterialAssessmentRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - materialID string
func (_e *MockMaterialAssessmentRepository_Expecter) Delete(ctx interface{}, materialID interface{}) *MockMaterialAssessmentRepository_Delete_Call {
	return &MockMaterialAssessmentRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, materialID)}
}

func (_c *MockMaterialAssessmentRepository_Delete_Call) Run(run func(ctx context.Context, materialID string)) *MockMaterialAssessmentRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMaterialAssessmentRepository_Delete_Call) Return(_a0 error) *MockMaterialAssessmentRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMaterialAssessmentRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockMaterialAssessmentRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: ctx, materialID
func (_m *MockMaterialAssessmentRepository) Exists(ctx context.Context, materialID string) (bool, error) {
	ret := _m.Called(ctx, materialID)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, materialID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, materialID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, materialID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMaterialAssessmentRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockMaterialAssessmentRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - materialID string
func (_e *MockMaterialAssessmentRepository_Expecter) Exists(ctx interface{}, materialID interface{}) *MockMaterialAssessmentRepository_Exists_Call {
	return &MockMaterialAssessmentRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, materialID)}
}

func (_c *MockMaterialAssessmentRepository_Exists_Call) Run(run func(ctx context.Context, materialID string)) *MockMaterialAssessmentRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMaterialAssessmentRepository_Exists_Call) Return(_a0 bool, _a1 error) *MockMaterialAssessmentRepository_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMaterialAssessmentRepository_Exists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockMaterialAssessmentRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// FindByDifficulty provides a mock function with given fields: ctx, difficulty, limit
func (_m *MockMaterialAssessmentRepository) FindByDifficulty(ctx context.Context, difficulty string, limit int64) ([]*entities.MaterialAssessment, error) {
	ret := _m.Called(ctx, difficulty, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByDifficulty")
	}

	var r0 []*entities.MaterialAssessment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) ([]*entities.MaterialAssessment, error)); ok {
		return rf(ctx, difficulty, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) []*entities.MaterialAssessment); ok {
		r0 = rf(ctx, difficulty, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.MaterialAssessment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, difficulty, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMaterialAssessmentRepository_FindByDifficulty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByDifficulty'
type MockMaterialAssessmentRepository_FindByDifficulty_Call struct {
	*mock.Call
}

// FindByDifficulty is a helper method to define mock.On call
//   - ctx context.Context
//   - difficulty string
//   - limit int64
func (_e *MockMaterialAssessmentRepository_Expecter) FindByDifficulty(ctx interface{}, difficulty interface{}, limit interface{}) *MockMaterialAssessmentRepository_FindByDifficulty_Call {
	return &MockMaterialAssessmentRepository_FindByDifficulty_Call{Call: _e.mock.On("FindByDifficulty", ctx, difficulty, limit)}
}

func (_c *MockMaterialAssessmentRepository_FindByDifficulty_Call) Run(run func(ctx context.Context, difficulty string, limit int64)) *MockMaterialAssessmentRepository_FindByDifficulty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *MockMaterialAssessmentRepository_FindByDifficulty_Call) Return(_a0 []*entities.MaterialAssessment, _a1 error) *MockMaterialAssessmentRepository_FindByDifficulty_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMaterialAssessmentRepository_FindByDifficulty_Call) RunAndReturn(run func(context.Context, string, int64) ([]*entities.MaterialAssessment, error)) *MockMaterialAssessmentRepository_FindByDifficulty_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockMaterialAssessmentRepository) FindByID(ctx context.Context, id primitive.ObjectID) (*entities.MaterialAssessment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.MaterialAssessment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) (*entities.MaterialAssessment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) *entities.MaterialAssessment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.MaterialAssessment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMaterialAssessmentRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockMaterialAssessmentRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id primitive.ObjectID
func (_e *MockMaterialAssessmentRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockMaterialAssessmentRepository_FindByID_Call {
	return &MockMaterialAssessmentRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockMaterialAssessmentRepository_FindByID_Call) Run(run func(ctx context.Context, id primitive.ObjectID)) *MockMaterialAssessmentRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(primitive.ObjectID))
	})
	return _c
}

func (_c *MockMaterialAssessmentRepository_FindByID_Call) Return(_a0 *entities.MaterialAssessment, _a1 error) *MockMaterialAssessmentRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMaterialAssessmentRepository_FindByID_Call) RunAndReturn(run func(context.Context, primitive.ObjectID) (*entities.MaterialAssessment, error)) *MockMaterialAssessmentRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByMaterialID provides a mock function with given fields: ctx, materialID
func (_m *MockMaterialAssessmentRepository) FindByMaterialID(ctx context.Context, materialID string) (*entities.MaterialAssessment, error) {
	ret := _m.Called(ctx, materialID)

	if len(ret) == 0 {
		panic("no return value specified for FindByMaterialID")
	}

	var r0 *entities.MaterialAssessment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.MaterialAssessment, error)); ok {
		return rf(ctx, materialID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.MaterialAssessment); ok {
		r0 = rf(ctx, materialID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.MaterialAssessment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, materialID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMaterialAssessmentRepository_FindByMaterialID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByMaterialID'
type MockMaterialAssessmentRepository_FindByMaterialID_Call struct {
	*mock.Call
}

// FindByMaterialID is a helper method to define mock.On call
//   - ctx context.Context
//   - materialID string
func (_e *MockMaterialAssessmentRepository_Expecter) FindByMaterialID(ctx interface{}, materialID interface{}) *MockMaterialAssessmentRepository_FindByMaterialID_Call {
	return &MockMaterialAssessmentRepository_FindByMaterialID_Call{Call: _e.mock.On("FindByMaterialID", ctx, materialID)}
}

func (_c *MockMaterialAssessmentRepository_FindByMaterialID_Call) Run(run func(ctx context.Context, materialID string)) *MockMaterialAssessmentRepository_FindByMaterialID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMaterialAssessmentRepository_FindByMaterialID_Call) Return(_a0 *entities.MaterialAssessment, _a1 error) *MockMaterialAssessmentRepository_FindByMaterialID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMaterialAssessmentRepository_FindByMaterialID_Call) RunAndReturn(run func(context.Context, string) (*entities.MaterialAssessment, error)) *MockMaterialAssessmentRepository_FindByMaterialID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByTotalQuestions provides a mock function with given fields: ctx, minQuestions, maxQuestions, limit
func (_m *MockMaterialAssessmentRepository) FindByTotalQuestions(ctx context.Context, minQuestions int, maxQuestions int, limit int64) ([]*entities.MaterialAssessment, error) {
	ret := _m.Called(ctx, minQuestions, maxQuestions, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByTotalQuestions")
	}

	var r0 []*entities.MaterialAssessment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int64) ([]*entities.MaterialAssessment, error)); ok {
		return rf(ctx, minQuestions, maxQuestions, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int64) []*entities.MaterialAssessment); ok {
		r0 = rf(ctx, minQuestions, maxQuestions, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.MaterialAssessment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int64) error); ok {
		r1 = rf(ctx, minQuestions, maxQuestions, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMaterialAssessmentRepository_FindByTotalQuestions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTotalQuestions'
type MockMaterialAssessmentRepository_FindByTotalQuestions_Call struct {
	*mock.Call
}

// FindByTotalQuestions is a helper method to define mock.On call
//   - ctx context.Context
//   - minQuestions int
//   - maxQuestions int
//   - limit int64
func (_e *MockMaterialAssessmentRepository_Expecter) FindByTotalQuestions(ctx interface{}, minQuestions interface{}, maxQuestions interface{}, limit interface{}) *MockMaterialAssessmentRepository_FindByTotalQuestions_Call {
	return &MockMaterialAssessmentRepository_FindByTotalQuestions_Call{Call: _e.mock.On("FindByTotalQuestions", ctx, minQuestions, maxQuestions, limit)}
}

func (_c *MockMaterialAssessmentRepository_FindByTotalQuestions_Call) Run(run func(ctx context.Context, minQuestions int, maxQuestions int, limit int64)) *MockMaterialAssessmentRepository_FindByTotalQuestions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(int64))
	})
	return _c
}

func (_c *MockMaterialAssessmentRepository_FindByTotalQuestions_Call) Return(_a0 []*entities.MaterialAssessment, _a1 error) *MockMaterialAssessmentRepository_FindByTotalQuestions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMaterialAssessmentRepository_FindByTotalQuestions_Call) RunAndReturn(run func(context.Context, int, int, int64) ([]*entities.MaterialAssessment, error)) *MockMaterialAssessmentRepository_FindByTotalQuestions_Call {
	_c.Call.Return(run)
	return _c
}

// FindRecent provides a mock function with given fields: ctx, limit
func (_m *MockMaterialAssessmentRepository) FindRecent(ctx context.Context, limit int64) ([]*entities.MaterialAssessment, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindRecent")
	}

	var r0 []*entities.MaterialAssessment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]*entities.MaterialAssessment, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*entities.MaterialAssessment); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.MaterialAssessment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMaterialAssessmentRepository_FindRecent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRecent'
type MockMaterialAssessmentRepository_FindRecent_Call struct {
	*mock.Call
}

// FindRecent is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int64
func (_e *MockMaterialAssessmentRepository_Expecter) FindRecent(ctx interface{}, limit interface{}) *MockMaterialAssessmentRepository_FindRecent_Call {
	return &MockMaterialAssessmentRepository_FindRecent_Call{Call: _e.mock.On("FindRecent", ctx, limit)}
}

func (_c *MockMaterialAssessmentRepository_FindRecent_Call) Run(run func(ctx context.Context, limit int64)) *MockMaterialAssessmentRepository_FindRecent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockMaterialAssessmentRepository_FindRecent_Call) Return(_a0 []*entities.MaterialAssessment, _a1 error) *MockMaterialAssessmentRepository_FindRecent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMaterialAssessmentRepository_FindRecent_Call) RunAndReturn(run func(context.Context, int64) ([]*entities.MaterialAssessment, error)) *MockMaterialAssessmentRepository_FindRecent_Call {
	_c.Call.Return(run)
	return _c
}

// GetAverageQuestionCount provides a mock function with given fields: ctx
func (_m *MockMaterialAssessmentRepository) GetAverageQuestionCount(ctx context.Context) (float64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAverageQuestionCount")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (float64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) float64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMaterialAssessmentRepository_GetAverageQuestionCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAverageQuestionCount'
type MockMaterialAssessmentRepository_GetAverageQuestionCount_Call struct {
	*mock.Call
}

// GetAverageQuestionCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMaterialAssessmentRepository_Expecter) GetAverageQuestionCount(ctx interface{}) *MockMaterialAssessmentRepository_GetAverageQuestionCount_Call {
	return &MockMaterialAssessmentRepository_GetAverageQuestionCount_Call{Call: _e.mock.On("GetAverageQuestionCount", ctx)}
}

func (_c *MockMaterialAssessmentRepository_GetAverageQuestionCount_Call) Run(run func(ctx context.Context)) *MockMaterialAssessmentRepository_GetAverageQuestionCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMaterialAssessmentRepository_GetAverageQuestionCount_Call) Return(_a0 float64, _a1 error) *MockMaterialAssessmentRepository_GetAverageQuestionCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMaterialAssessmentRepository_GetAverageQuestionCount_Call) RunAndReturn(run func(context.Context) (float64, error)) *MockMaterialAssessmentRepository_GetAverageQuestionCount_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, assessment
func (_m *MockMaterialAssessmentRepository) Update(ctx context.Context, assessment *entities.MaterialAssessment) error {
	ret := _m.Called(ctx, assessment)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.MaterialAssessment) error); ok {
		r0 = rf(ctx, assessment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMaterialAssessmentRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockMaterialAssessmentRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - assessment *entities.MaterialAssessment
func (_e *MockMaterialAssessmentRepository_Expecter) Update(ctx interface{}, assessment interface{}) *MockMaterialAssessmentRepository_Update_Call {
	return &MockMaterialAssessmentRepository_Update_Call{Call: _e.mock.On("Update", ctx, assessment)}
}

func (_c *MockMaterialAssessmentRepository_Update_Call) Run(run func(ctx context.Context, assessment *entities.MaterialAssessment)) *MockMaterialAssessmentRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.MaterialAssessment))
	})
	return _c
}

func (_c *MockMaterialAssessmentRepository_Update_Call) Return(_a0 error) *MockMaterialAssessmentRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMaterialAssessmentRepository_Update_Call) RunAndReturn(run func(context.Context, *entities.MaterialAssessment) error) *MockMaterialAssessmentRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMaterialAssessmentRepository creates a new instance of MockMaterialAssessmentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMaterialAssessmentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMaterialAssessmentRepository {
	mock := &MockMaterialAssessmentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
