// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/EduGoGroup/edugo-infrastructure/mongodb/entities"
	mock "github.com/stretchr/testify/mock"

	"go.mongodb.org/mongo-driver/v2/bson"
)

// MockMaterialSummaryRepository is an autogenerated mock type for the MaterialSummaryRepository type
type MockMaterialSummaryRepository struct {
	mock.Mock
}

type MockMaterialSummaryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMaterialSummaryRepository) EXPECT() *MockMaterialSummaryRepository_Expecter {
	return &MockMaterialSummaryRepository_Expecter{mock: &_m.Mock}
}

// CountByLanguage provides a mock function with given fields: ctx, language
func (_m *MockMaterialSummaryRepository) CountByLanguage(ctx context.Context, language string) (int64, error) {
	ret := _m.Called(ctx, language)

	if len(ret) == 0 {
		panic("no return value specified for CountByLanguage")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, language)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, language)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, language)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMaterialSummaryRepository_CountByLanguage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByLanguage'
type MockMaterialSummaryRepository_CountByLanguage_Call struct {
	*mock.Call
}

// CountByLanguage is a helper method to define mock.On call
//   - ctx context.Context
//   - language string
func (_e *MockMaterialSummaryRepository_Expecter) CountByLanguage(ctx interface{}, language interface{}) *MockMaterialSummaryRepository_CountByLanguage_Call {
	return &MockMaterialSummaryRepository_CountByLanguage_Call{Call: _e.mock.On("CountByLanguage", ctx, language)}
}

func (_c *MockMaterialSummaryRepository_CountByLanguage_Call) Run(run func(ctx context.Context, language string)) *MockMaterialSummaryRepository_CountByLanguage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMaterialSummaryRepository_CountByLanguage_Call) Return(_a0 int64, _a1 error) *MockMaterialSummaryRepository_CountByLanguage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMaterialSummaryRepository_CountByLanguage_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockMaterialSummaryRepository_CountByLanguage_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, summary
func (_m *MockMaterialSummaryRepository) Create(ctx context.Context, summary *entities.MaterialSummary) error {
	ret := _m.Called(ctx, summary)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.MaterialSummary) error); ok {
		r0 = rf(ctx, summary)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMaterialSummaryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMaterialSummaryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - summary *entities.MaterialSummary
func (_e *MockMaterialSummaryRepository_Expecter) Create(ctx interface{}, summary interface{}) *MockMaterialSummaryRepository_Create_Call {
	return &MockMaterialSummaryRepository_Create_Call{Call: _e.mock.On("Create", ctx, summary)}
}

func (_c *MockMaterialSummaryRepository_Create_Call) Run(run func(ctx context.Context, summary *entities.MaterialSummary)) *MockMaterialSummaryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.MaterialSummary))
	})
	return _c
}

func (_c *MockMaterialSummaryRepository_Create_Call) Return(_a0 error) *MockMaterialSummaryRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMaterialSummaryRepository_Create_Call) RunAndReturn(run func(context.Context, *entities.MaterialSummary) error) *MockMaterialSummaryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, materialID
func (_m *MockMaterialSummaryRepository) Delete(ctx context.Context, materialID string) error {
	ret := _m.Called(ctx, materialID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, materialID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMaterialSummaryRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockMaterialSummaryRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - materialID string
func (_e *MockMaterialSummaryRepository_Expecter) Delete(ctx interface{}, materialID interface{}) *MockMaterialSummaryRepository_Delete_Call {
	return &MockMaterialSummaryRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, materialID)}
}

func (_c *MockMaterialSummaryRepository_Delete_Call) Run(run func(ctx context.Context, materialID string)) *MockMaterialSummaryRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMaterialSummaryRepository_Delete_Call) Return(_a0 error) *MockMaterialSummaryRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMaterialSummaryRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockMaterialSummaryRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: ctx, materialID
func (_m *MockMaterialSummaryRepository) Exists(ctx context.Context, materialID string) (bool, error) {
	ret := _m.Called(ctx, materialID)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, materialID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, materialID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, materialID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMaterialSummaryRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockMaterialSummaryRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - materialID string
func (_e *MockMaterialSummaryRepository_Expecter) Exists(ctx interface{}, materialID interface{}) *MockMaterialSummaryRepository_Exists_Call {
	return &MockMaterialSummaryRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, materialID)}
}

func (_c *MockMaterialSummaryRepository_Exists_Call) Run(run func(ctx context.Context, materialID string)) *MockMaterialSummaryRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMaterialSummaryRepository_Exists_Call) Return(_a0 bool, _a1 error) *MockMaterialSummaryRepository_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMaterialSummaryRepository_Exists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockMaterialSummaryRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockMaterialSummaryRepository) FindByID(ctx context.Context, id bson.ObjectID) (*entities.MaterialSummary, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.MaterialSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bson.ObjectID) (*entities.MaterialSummary, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bson.ObjectID) *entities.MaterialSummary); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.MaterialSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bson.ObjectID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMaterialSummaryRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockMaterialSummaryRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id bson.ObjectID
func (_e *MockMaterialSummaryRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockMaterialSummaryRepository_FindByID_Call {
	return &MockMaterialSummaryRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockMaterialSummaryRepository_FindByID_Call) Run(run func(ctx context.Context, id bson.ObjectID)) *MockMaterialSummaryRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bson.ObjectID))
	})
	return _c
}

func (_c *MockMaterialSummaryRepository_FindByID_Call) Return(_a0 *entities.MaterialSummary, _a1 error) *MockMaterialSummaryRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMaterialSummaryRepository_FindByID_Call) RunAndReturn(run func(context.Context, bson.ObjectID) (*entities.MaterialSummary, error)) *MockMaterialSummaryRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByLanguage provides a mock function with given fields: ctx, language, limit
func (_m *MockMaterialSummaryRepository) FindByLanguage(ctx context.Context, language string, limit int64) ([]*entities.MaterialSummary, error) {
	ret := _m.Called(ctx, language, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByLanguage")
	}

	var r0 []*entities.MaterialSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) ([]*entities.MaterialSummary, error)); ok {
		return rf(ctx, language, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) []*entities.MaterialSummary); ok {
		r0 = rf(ctx, language, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.MaterialSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, language, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMaterialSummaryRepository_FindByLanguage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByLanguage'
type MockMaterialSummaryRepository_FindByLanguage_Call struct {
	*mock.Call
}

// FindByLanguage is a helper method to define mock.On call
//   - ctx context.Context
//   - language string
//   - limit int64
func (_e *MockMaterialSummaryRepository_Expecter) FindByLanguage(ctx interface{}, language interface{}, limit interface{}) *MockMaterialSummaryRepository_FindByLanguage_Call {
	return &MockMaterialSummaryRepository_FindByLanguage_Call{Call: _e.mock.On("FindByLanguage", ctx, language, limit)}
}

func (_c *MockMaterialSummaryRepository_FindByLanguage_Call) Run(run func(ctx context.Context, language string, limit int64)) *MockMaterialSummaryRepository_FindByLanguage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *MockMaterialSummaryRepository_FindByLanguage_Call) Return(_a0 []*entities.MaterialSummary, _a1 error) *MockMaterialSummaryRepository_FindByLanguage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMaterialSummaryRepository_FindByLanguage_Call) RunAndReturn(run func(context.Context, string, int64) ([]*entities.MaterialSummary, error)) *MockMaterialSummaryRepository_FindByLanguage_Call {
	_c.Call.Return(run)
	return _c
}

// FindByMaterialID provides a mock function with given fields: ctx, materialID
func (_m *MockMaterialSummaryRepository) FindByMaterialID(ctx context.Context, materialID string) (*entities.MaterialSummary, error) {
	ret := _m.Called(ctx, materialID)

	if len(ret) == 0 {
		panic("no return value specified for FindByMaterialID")
	}

	var r0 *entities.MaterialSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.MaterialSummary, error)); ok {
		return rf(ctx, materialID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.MaterialSummary); ok {
		r0 = rf(ctx, materialID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.MaterialSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, materialID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMaterialSummaryRepository_FindByMaterialID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByMaterialID'
type MockMaterialSummaryRepository_FindByMaterialID_Call struct {
	*mock.Call
}

// FindByMaterialID is a helper method to define mock.On call
//   - ctx context.Context
//   - materialID string
func (_e *MockMaterialSummaryRepository_Expecter) FindByMaterialID(ctx interface{}, materialID interface{}) *MockMaterialSummaryRepository_FindByMaterialID_Call {
	return &MockMaterialSummaryRepository_FindByMaterialID_Call{Call: _e.mock.On("FindByMaterialID", ctx, materialID)}
}

func (_c *MockMaterialSummaryRepository_FindByMaterialID_Call) Run(run func(ctx context.Context, materialID string)) *MockMaterialSummaryRepository_FindByMaterialID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMaterialSummaryRepository_FindByMaterialID_Call) Return(_a0 *entities.MaterialSummary, _a1 error) *MockMaterialSummaryRepository_FindByMaterialID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMaterialSummaryRepository_FindByMaterialID_Call) RunAndReturn(run func(context.Context, string) (*entities.MaterialSummary, error)) *MockMaterialSummaryRepository_FindByMaterialID_Call {
	_c.Call.Return(run)
	return _c
}

// FindRecent provides a mock function with given fields: ctx, limit
func (_m *MockMaterialSummaryRepository) FindRecent(ctx context.Context, limit int64) ([]*entities.MaterialSummary, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindRecent")
	}

	var r0 []*entities.MaterialSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]*entities.MaterialSummary, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*entities.MaterialSummary); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.MaterialSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMaterialSummaryRepository_FindRecent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRecent'
type MockMaterialSummaryRepository_FindRecent_Call struct {
	*mock.Call
}

// FindRecent is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int64
func (_e *MockMaterialSummaryRepository_Expecter) FindRecent(ctx interface{}, limit interface{}) *MockMaterialSummaryRepository_FindRecent_Call {
	return &MockMaterialSummaryRepository_FindRecent_Call{Call: _e.mock.On("FindRecent", ctx, limit)}
}

func (_c *MockMaterialSummaryRepository_FindRecent_Call) Run(run func(ctx context.Context, limit int64)) *MockMaterialSummaryRepository_FindRecent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockMaterialSummaryRepository_FindRecent_Call) Return(_a0 []*entities.MaterialSummary, _a1 error) *MockMaterialSummaryRepository_FindRecent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMaterialSummaryRepository_FindRecent_Call) RunAndReturn(run func(context.Context, int64) ([]*entities.MaterialSummary, error)) *MockMaterialSummaryRepository_FindRecent_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, summary
func (_m *MockMaterialSummaryRepository) Update(ctx context.Context, summary *entities.MaterialSummary) error {
	ret := _m.Called(ctx, summary)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.MaterialSummary) error); ok {
		r0 = rf(ctx, summary)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMaterialSummaryRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockMaterialSummaryRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - summary *entities.MaterialSummary
func (_e *MockMaterialSummaryRepository_Expecter) Update(ctx interface{}, summary interface{}) *MockMaterialSummaryRepository_Update_Call {
	return &MockMaterialSummaryRepository_Update_Call{Call: _e.mock.On("Update", ctx, summary)}
}

func (_c *MockMaterialSummaryRepository_Update_Call) Run(run func(ctx context.Context, summary *entities.MaterialSummary)) *MockMaterialSummaryRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.MaterialSummary))
	})
	return _c
}

func (_c *MockMaterialSummaryRepository_Update_Call) Return(_a0 error) *MockMaterialSummaryRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMaterialSummaryRepository_Update_Call) RunAndReturn(run func(context.Context, *entities.MaterialSummary) error) *MockMaterialSummaryRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMaterialSummaryRepository creates a new instance of MockMaterialSummaryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMaterialSummaryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMaterialSummaryRepository {
	mock := &MockMaterialSummaryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
