// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	storage "github.com/EduGoGroup/edugo-worker/internal/infrastructure/storage"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, key
func (_m *MockClient) Delete(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockClient_Expecter) Delete(ctx interface{}, key interface{}) *MockClient_Delete_Call {
	return &MockClient_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockClient_Delete_Call) Run(run func(ctx context.Context, key string)) *MockClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_Delete_Call) Return(_a0 error) *MockClient_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Download provides a mock function with given fields: ctx, key
func (_m *MockClient) Download(ctx context.Context, key string) (io.ReadCloser, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MockClient_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockClient_Expecter) Download(ctx interface{}, key interface{}) *MockClient_Download_Call {
	return &MockClient_Download_Call{Call: _e.mock.On("Download", ctx, key)}
}

func (_c *MockClient_Download_Call) Run(run func(ctx context.Context, key string)) *MockClient_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_Download_Call) Return(_a0 io.ReadCloser, _a1 error) *MockClient_Download_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_Download_Call) RunAndReturn(run func(context.Context, string) (io.ReadCloser, error)) *MockClient_Download_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: ctx, key
func (_m *MockClient) Exists(ctx context.Context, key string) (bool, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockClient_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockClient_Expecter) Exists(ctx interface{}, key interface{}) *MockClient_Exists_Call {
	return &MockClient_Exists_Call{Call: _e.mock.On("Exists", ctx, key)}
}

func (_c *MockClient_Exists_Call) Run(run func(ctx context.Context, key string)) *MockClient_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_Exists_Call) Return(_a0 bool, _a1 error) *MockClient_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_Exists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockClient_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetadata provides a mock function with given fields: ctx, key
func (_m *MockClient) GetMetadata(ctx context.Context, key string) (*storage.FileMetadata, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetMetadata")
	}

	var r0 *storage.FileMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*storage.FileMetadata, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *storage.FileMetadata); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.FileMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetadata'
type MockClient_GetMetadata_Call struct {
	*mock.Call
}

// GetMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockClient_Expecter) GetMetadata(ctx interface{}, key interface{}) *MockClient_GetMetadata_Call {
	return &MockClient_GetMetadata_Call{Call: _e.mock.On("GetMetadata", ctx, key)}
}

func (_c *MockClient_GetMetadata_Call) Run(run func(ctx context.Context, key string)) *MockClient_GetMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_GetMetadata_Call) Return(_a0 *storage.FileMetadata, _a1 error) *MockClient_GetMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetMetadata_Call) RunAndReturn(run func(context.Context, string) (*storage.FileMetadata, error)) *MockClient_GetMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function with given fields: ctx, key, content
func (_m *MockClient) Upload(ctx context.Context, key string, content io.Reader) error {
	ret := _m.Called(ctx, key, content)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader) error); ok {
		r0 = rf(ctx, key, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockClient_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - content io.Reader
func (_e *MockClient_Expecter) Upload(ctx interface{}, key interface{}, content interface{}) *MockClient_Upload_Call {
	return &MockClient_Upload_Call{Call: _e.mock.On("Upload", ctx, key, content)}
}

func (_c *MockClient_Upload_Call) Run(run func(ctx context.Context, key string, content io.Reader)) *MockClient_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader))
	})
	return _c
}

func (_c *MockClient_Upload_Call) Return(_a0 error) *MockClient_Upload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Upload_Call) RunAndReturn(run func(context.Context, string, io.Reader) error) *MockClient_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
